name: "On commit"

on: push

permissions: read-all

jobs:
  binary:
    name: Binary
    strategy:
      fail-fast: true
      matrix:
        goos:
          - linux
        goarch:
          - amd64
          - arm64
    uses: PossibleLlama/workflows/.github/workflows/golang-binary.yaml@v0.1.7
    with:
      source-path: "./exec/cli/main.go"
      build-flags: "-ldflags=\"-w -s -X 'main.VERSION=$(git rev-list -1 HEAD)'\""
      os: ${{ matrix.goos }}
      arch: ${{ matrix.goarch }}

  linting:
    name: Linting
    uses: PossibleLlama/workflows/.github/workflows/golang-linting.yaml@v0.1.7
    with:
      source-path: "./exec/cli/main.go"

  test-small-correctness:
    name: Test small correctness
    uses: PossibleLlama/workflows/.github/workflows/golang-testing-small-correctness.yaml@v0.1.7
