name: "On commit"

on: push

permissions: read-all

jobs:
  binary:
    name: Binary
    strategy:
      fail-fast: true
      matrix:
        goos:
          - linux
          - windows
        goarch:
          - amd64
          - arm64
    uses: PossibleLlama/workflows/.github/workflows/golang-binary.yaml@v0.1.4
    with:
      source-path: "./exec/cli/main.go"
      build-flags: "-ldflags=\"-w -s -X 'main.VERSION=$(git rev-list -1 HEAD)'\""
      os: ${{ matrix.goos }}
      arch: ${{ matrix.goarch }}

  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version-file: "./go.mod"

    - name: Check formatting
      run: go fmt ./...

    - name: Check vet
      run: go vet ./...

    - name: Check linting
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-pkg-cache: true
        args: --issues-exit-code=0 --out-format checkstyle -v ./... > ./lint.out

    - name: Store linting report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Linting report
        path: ./lint.out
        if-no-files-found: ignore
        retention-days: 2

  test-small-correctness:
    name: Test small correctness
    uses: PossibleLlama/workflows/.github/workflows/golang-testing-small-correctness.yaml@v0.1.1
