name: "On commit - Main"

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  binary:
    name: Binary
    strategy:
      fail-fast: false
      matrix:
        goos:
          - linux
          - darwin
          - windows
        goarch:
          - amd64
          - arm64
    uses: PossibleLlama/workflows/.github/workflows/golang-binary.yaml@v0.2.15
    with:
      source-path: "./exec/cli/main.go"
      build-flags: "-ldflags=\"-w -s -X 'main.VERSION=$(git rev-list -1 HEAD)'\""
      os: ${{ matrix.goos }}
      arch: ${{ matrix.goarch }}
      retention-days: 30

  security:
    name: Security checks
    permissions:
      security-events: write
    uses: PossibleLlama/workflows/.github/workflows/golang-security.yaml@v0.2.15
    with:
      upload-sarif: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - binary
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"

    - name: Download app
      uses: actions/download-artifact@v4
      with:
        path: .

    - name: Move binaries
      run: |
        mv ./Binaries-darwin-amd64/* .
        mv ./Binaries-darwin-arm64/* .
        mv ./Binaries-linux-amd64/* .
        mv ./Binaries-linux-arm64/* .
        mv ./Binaries-windows-amd64/* .
        mv ./Binaries-windows-arm64/* .

    - name: Semantic Release
      run: |
        npm i @semantic-release/commit-analyzer @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits
        npx semantic-release@21
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
