name: "On commit"

on: push

permissions: read-all

jobs:
  binary:
    name: Binary
    strategy:
      fail-fast: true
      matrix:
        goos:
          - linux
        goarch:
          - amd64
          - arm64
    uses: PossibleLlama/workflows/.github/workflows/golang-binary.yaml@v0.2.17
    with:
      source-path: "./exec/cli/main.go"
      build-flags: "-ldflags=\"-w -s -X 'main.VERSION=$(git rev-list -1 HEAD)'\""
      os: ${{ matrix.goos }}
      arch: ${{ matrix.goarch }}

  linting:
    name: Linting
    uses: PossibleLlama/workflows/.github/workflows/golang-linting.yaml@v0.2.17
    with:
      source-path: "./exec/cli/main.go"

  test-small:
    name: Test small
    uses: PossibleLlama/workflows/.github/workflows/golang-testing-small.yaml@v0.2.17
    with:
      enable-performance: false
      enable-fuzz: false
