name: "Security scans"

on: push

jobs:
  SCA:
    name: SCA
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version-file: "./go.mod"

    - name: Write Go List
      run: go list -json -m > go.list

    - name: Run Nancy
      uses: sonatype-nexus-community/nancy-github-action@main

  SAST:
    name: SAST
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"

      # TODO check on progress of https://github.com/golang/go/issues/61347
      - name: Govulncheck
        uses: golang/govulncheck-action@v1
        with:
            go-package: ./...
