name: vhs
on:
  push:
    paths:
      - docs/*.tape

jobs:
  artifact-vhs:
    name: "Create VHS artifact"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"

      - name: Get dependencies
        run: go mod download

      - name: Install binary
        run: |
          go build -ldflags="-w -s -X 'main.VERSION=demo'" -o "./commit-check" ./exec/cli/main.go
          mv ./commit-check /usr/local/bin/commit-check

      - name: Setup demo repository
        run: |
          echo -e "Hide\nType \"cd ../demo && clear\"\nEnter\nShow\n$(cat $PWD/docs/basic.tape)" > $PWD/docs/basic.tape
          echo -e "Hide\nType \"cd ../demo && clear\"\nEnter\nShow\n$(cat $PWD/docs/dry-run.tape)" > $PWD/docs/dry-run.tape
          mkdir ../demo
          cd ../demo
          git init --initial-branch=main
          git config --global user.name "vhs-action"
          git config --global user.email "actions@github.com"
          touch demo.txt
          git add demo.txt

      - name: Generate basic
        uses: charmbracelet/vhs-action@v1
        with:
          path: "docs/basic.tape"

      - name: Generate dry run
        uses: charmbracelet/vhs-action@v1
        with:
          path: "docs/dry-run.tape"

      - name: Commit back changes
        run: |
          mv *.gif docs/examples/
          git add docs/examples/*.gif
          git config --global user.name "vhs-action"
          git config --global user.email "actions@github.com"
          git commit -m "Updated vhs [skip ci]" || true
          git push
